/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import static Vista.VistaMain.alumnData;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author silvi
 */
public class VistaAlumno extends javax.swing.JInternalFrame {

    private Alumno aSelected = null;
    private int iSelected = 0;
    
    public VistaAlumno() {
        initComponents();
        readingTable();
        jtTablaAlumnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTablaAlumnos.setShowHorizontalLines(true);
        jtTablaAlumnos.setShowVerticalLines(true);
        jtTablaAlumnos.putClientProperty("JTable.showInactiveSelection", true);
        jtTablaAlumnos.getSelectionModel().addListSelectionListener(
            new javax.swing.event.ListSelectionListener() {
                @Override
                public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    if (!evt.getValueIsAdjusting()) {
                        int selection = jtTablaAlumnos.getSelectedRow();

                        if (selection != -1) {
                            iSelected = selection;
                            aSelected = alumnData.getById(
                                (int) jtTablaAlumnos.getValueAt(selection, 0)
                            );
                        }
                    }
                }
            }
        );
    }
    
    public void readingTable() {
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        table.addColumn("Id");
        table.addColumn("Dni");
        table.addColumn("Nombre");
        table.addColumn("Fecha de Nacimiento");
        table.addColumn("Activo");
        jtTablaAlumnos.setModel(table);
        
        jtTablaAlumnos.getColumnModel().getColumn(0).setPreferredWidth(30);
        jtTablaAlumnos.getColumnModel().getColumn(1).setPreferredWidth(80);
        jtTablaAlumnos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jtTablaAlumnos.getColumnModel().getColumn(3).setPreferredWidth(120);
        jtTablaAlumnos.getColumnModel().getColumn(4).setPreferredWidth(80);
        
        for (Alumno a: alumnData.getList()) {
            int iteration = 0;
            String activo = "Inactivo";
            if (a.getActivo()) activo = "Activo";
            table.addRow(new Object[]{a.getIdAlumno(),a.getDni(),a.getNombre(),a.getFecNac(),activo});
        }
        
        jtTablaAlumnos.setModel(table);
        
        if (aSelected != null) {
            if (jtTablaAlumnos.getRowCount() > iSelected) {
                jtTablaAlumnos.setRowSelectionInterval(iSelected, iSelected);
            }
        }
            
        changeVisuals();
    }
    
    public void changeVisuals() {
        if (aSelected != null) {
            btnModificar.setEnabled(true);
            btnBorrar.setEnabled(true);
            btnAlta.setEnabled(!aSelected.getActivo());
            btnBaja.setEnabled(aSelected.getActivo());
        }else{
            btnModificar.setEnabled(false);
            btnBorrar.setEnabled(false);
            btnAlta.setEnabled(false);
            btnBaja.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListaAlumnos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaAlumnos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();

        setClosable(true);

        lblListaAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblListaAlumnos.setText("Lista de Alumnos:");

        jtTablaAlumnos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtTablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaAlumnos.setToolTipText("");
        jtTablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaAlumnos);

        btnAgregar.setText("Agregar");

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);

        btnBorrar.setText("Eliminar");
        btnBorrar.setEnabled(false);
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnAlta.setText("Alta");
        btnAlta.setEnabled(false);
        btnAlta.addActionListener(this::btnAltaActionPerformed);

        btnBaja.setText("Baja");
        btnBaja.setEnabled(false);
        btnBaja.addActionListener(this::btnBajaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnBorrar)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtTablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaAlumnosMouseClicked
        changeVisuals();
    }//GEN-LAST:event_jtTablaAlumnosMouseClicked

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        aSelected.setActivo(true);
        alumnData.update(aSelected);
        readingTable();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        aSelected.setActivo(false);
        alumnData.update(aSelected);
        readingTable();
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int index = iSelected;
        alumnData.remove(aSelected.getIdAlumno());
        readingTable();
        int rowCount = jtTablaAlumnos.getRowCount();
        if (rowCount > 0) {
            int newIndex = Math.min(index, rowCount - 1);
            jtTablaAlumnos.setRowSelectionInterval(newIndex, newIndex);
            int idAlumno = (int) jtTablaAlumnos.getValueAt(newIndex, 0);
            aSelected = alumnData.getById(idAlumno);
        } else {
            aSelected = null;
        }
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtTablaAlumnos;
    private javax.swing.JLabel lblListaAlumnos;
    // End of variables declaration//GEN-END:variables
}
